package com.example.spring.windmill.mapper.generator;

import com.example.spring.windmill.dataobject.generator.SeqDO;

public interface SeqDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq
     *
     * @mbg.generated Wed Mar 27 23:24:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq
     *
     * @mbg.generated Wed Mar 27 23:24:07 CST 2019
     */
    int insert(SeqDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq
     *
     * @mbg.generated Wed Mar 27 23:24:07 CST 2019
     */
    int insertSelective(SeqDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq
     *
     * @mbg.generated Wed Mar 27 23:24:07 CST 2019
     */
    SeqDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq
     *
     * @mbg.generated Wed Mar 27 23:24:07 CST 2019
     */
    int updateByPrimaryKeySelective(SeqDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq
     *
     * @mbg.generated Wed Mar 27 23:24:07 CST 2019
     */
    int updateByPrimaryKey(SeqDO record);
}