spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/alvin?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.163.com
    username: wind@163.com
    password: mima    #此处输入你自己的密码
    default-encoding: UTF-8
mail:
  fromMail:
    addr: wind@163.com

mybatis:
    mapperLocations: classpath*:com/example/spring/windmill/mybatis/mapper/**/*.xml